-- FlowsState table schema
CREATE TABLE IF NOT EXISTS flows_state (
  id INT AUTO_INCREMENT PRIMARY KEY,
  flow_token VARCHAR(255) NOT NULL UNIQUE,
  screen VARCHAR(100),
  phone_number VARCHAR(20) NOT NULL,
  sport JSON,
  date JSON,
  duration VARCHAR(20),
  time_slot VARCHAR(100),
  name VARCHAR(100),
  email VARCHAR(100),
  total_amount VARCHAR(20),
  original_amount VARCHAR(20),
  discount_info VARCHAR(255),
  is_date_enabled BOOLEAN DEFAULT FALSE,
  is_duration_enabled BOOLEAN DEFAULT FALSE,
  is_time_slots_enabled BOOLEAN DEFAULT FALSE,
  is_footer_enabled BOOLEAN DEFAULT FALSE,
  min_date VARCHAR(20),
  max_date VARCHAR(20),
  processed_messages JSON,
  available_slots JSON,
  selected_slot_id VARCHAR(50),
  payment_id VARCHAR(100),
  payment_status VARCHAR(20) DEFAULT 'pending',
  booking_id INT,
  language VARCHAR(10) DEFAULT 'en',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX (phone_number),
  INDEX (flow_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;